### PR TITLE
Added Codec.FFmpeg.Buffer module.

### PR DESCRIPTION
**Pull request by wowofbob**
This module provides API for copying image data from `AVFrame`
plus FFI declarations for the underlying FFmpeg functions.

I find it useful for filling up SDL's textures. I'm just not sure should it be separate module or not.

Example of usage (the use of module is labeled by `!!!` in comments):

````haskell
import qualified Codec.FFmpeg        as FFmpeg
import qualified Codec.FFmpeg.Buffer as FFmpeg (copyImage)
import qualified SDL as SDL

-- Creates a texture from frame.
createTextureFromFrame
  :: SDL.Renderer
  -> SDL.PixelFormat
  -> SDL.TextureAccess
  -> FFmpeg.AVFrame
  -> IO SDL.Texture
createTextureFromFrame r pf ta f =
  do
  
    -- Get frame width.
    w <- FFmpeg.getWidth f
    
    -- Get frame height.
    h <- FFmpeg.getHeight f
    
    -- Create empty texture.
    texture <- SDL.createTexture
                 r
                 pf
                 ta
                 $ SDL.V2 w h

    -- !!! Copy image from frame (using copyImage from Codec.FFmpeg.Buffer).
    img <- FFmpeg.copyImage f
    
    -- Get frame's line size.
    s <- FFmpeg.getLineSize f

    -- Update texture by image from frame.
    texture' <- SDL.updateTexture
                  texture
                  -- Entire texture.
                  Nothing
                  img -- !!!
                  s
                  
    return texture'
````

### CODE REVIEW

**Comment by acowley** [comment]
Thank you, @wowofbob! This seems to overlap with the `Codec.FFmpeg.Juicy` module, do you think we could combine them to some extent? The SDL example you show here is really nicely compact, so we'd want to preserve that usability, but I've been using the `Juicy` API for this sort of thing for a while, and now hope we can somehow make it all of a piece.

For instance, the `Juicy` module copies things into a `Storable` `Vector`, which isn't far removed from a `ByteString`. I try to stick to `Vector`s because I can coerce them to different pixel formats and still use the `vector` package's rich API to safely control indexing into them.

It may be that your approach to copying the `AVFrame` data is superior to what is in the `Juicy` module, so we could switch to using that as the foundation, and layer the `Image` parts on top of that. Or we could offer a `ByteString`-friendly API to the existing `AVFrame`-copying code. Either way makes sense to me, and I'd appreciate any input you have on how to piece things together.

**Comment by wowofbob** [comment]
@acowley , thanks for reply!

I like your idea about switching `Juicy`'s foundation. It sounds natural. Plus, it means adding frame copying functions which might be used for other purposes too. For example, for `ByteString` filling.

So I tried to replace copying approach in `Juicy` by native ffmpeg functions.

I got several questions which makes me confused.

1. Am I right that once frame is loaded, it's format is set, and when `toJuicy` or `toJuicyImage` are called, the output image will have the same format as source frame?

2. There is a field `lineSize` in `AVFrame` structure. It is a number of bytes in frame's row.
If we know frame's format, then we know the size of pixel in bytes. In some cases, when I multiply this value on frame's width, I get a result which isn't equal to a value of `lineSize` field of frame. It was a source of errors in my first attempts. Why does this happen, is it because the line of frame contains some extra padding bytes at the end?

Now I use `avPixelStride` to get the number of bytes in pixel. Then I multiply it on frame's width. After that I have a number of bytes in frame's row. Then I use that value to calculate frame's alignment. This way, I'm getting correct values for buffer size from `av_image_get_buffer_size`: they are equal to `h * dstStride` used in `Juicy` for buffer size. But the usage of `avPixelStride` forces me to be in `Maybe` monad. I'm not sure how does it hit performance.

My files are not finished for pull-request yet until I resolve my questions. I plan to remove `ByteString` API there in order to leave library minimal. Also, I want to remove my module at all and put it's functions to `Codec.FFmpeg.Common`. Can I do this or should I place them in another module? They are just FFI declarations and their wrappers plus one utility function for calculating alignment. So I guess they fit.

**Comment by wowofbob** [comment]
Added video player demo: vplay. It has simple video synchronization but doesn't play sound.

**Comment by acowley** [comment]
This is looking very good, @wowofbob! Let me know when you want to merge it into master. I think we should re-name the build flags as `BuildDemo` is upsettingly terrible at this point 😄

For the video player demo, I'd also like to try re-using the texture rather than creating a new one on every frame (if I'm understanding the code correctly).

These aren't blockers, just things I'd like to do moving forward. Thank you so much for the thoughtful work you've already put in!

**Comment by wowofbob** [comment]
@acowley thanks!

I'm not sure about names for build flags. So I can put any which you think are good into merge.
Yes, video player in demo doesn't re-use texture. That's what I'm going to change :)

I'll let you know when I'll be ready to merge. Thank you again!

**Comment by wowofbob** [comment]
@acowley I guess I'm ready to merge into master.

I polished demo a little and edited comments so they would look better on hackage.

I want to merge something I already have instead of polishing it forever I guess :)

**Comment by acowley** [comment]
This is really fantastic, thank you @wowofbob!

**Pull request merged**
