### PR TITLE
Add a configuration field to the camera (API change!)

### PR DESCRIPTION
**Pull request by TomMD**
I was noticing ffmpeg was suddenly selecting the lowest resolution by default
where it was previously selecting something decent. Now users can use
'defaultCameraConfig' or specify the resolution and framerate of their choice.

### CODE REVIEW

**Comment by TomMD** [comment]
Hurm.. .or maybe I should have left the default resolution as `Nothing`.  Let me know if you'd rather have that and I'll rebase.

**Comment by acowley** [comment]
Yeah, I think it has to be `Nothing` by default. While the frame rate is probably fine, resolutions certainly vary a lot between cameras.

**Comment by TomMD** [comment]
@acowley Fixed - the default resolution is `Nothing`.

**Comment by TomMD** [comment]
The demo works for me and using the option with arbitrary (supported) resolutions also functions - so I think we're good here.

**Comment by acowley** [comment]
Thanks! I'd really like to sort out the Travis tests. There's an issue to add this to Stackage, which I'd like to do, but the tests need sorting. Have you by any chance looked at the definitions that we need to add to our stub definitions used on Travis?

**Pull request merged**
